# -*- coding: utf-8 -*-
"""ner_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Xx9N_o4rnS7c-C33FIJk-pUw2r_WKX2
"""

import spacy
import streamlit as st

# Mapping from spaCy labels to CoNLL labels
spacy2conll = {
    "PERSON": "PER",
    "NORP": "MISC",
    "ORG": "ORG",
    "GPE": "GPE",
    "LOC": "LOC",
    "FAC": "FAC",
    "MISC": "MISC",
    "PRODUCT": "PROD",
    "EVENT": "EVENT",
    "DATE": "DATE",
    "MONEY": "MONEY"
}

# Human-friendly descriptions for spaCy entity types
entity_descriptions = {
    "PERSON": "People, including fictional characters",
    "NORP": "Nationalities, religious or political groups",
    "ORG": "Organizations (companies, agencies, institutions)",
    "GPE": "Countries, cities, states",
    "LOC": "Locations (non-political, e.g., mountains, rivers)",
    "FAC": "Facilities (buildings, airports, highways)",
    "MISC": "Miscellaneous entities",
    "PRODUCT": "Products (objects, vehicles, foods, etc.)",
    "EVENT": "Named events (wars, sports events, etc.)",
    "DATE": "Specific dates or periods",
    "MONEY": "Monetary values"
}

# Colors for entity types
colors = {
    "PERSON": "lightgreen",
    "ORG": "lightblue",
    "GPE": "orange",
    "DATE": "pink",
    "MONEY": "yellow",
    "PRODUCT": "violet",
    "LOC": "lightcoral",
    "MISC": "lightgrey",
    "EVENT": "khaki",
    "FAC": "wheat",
    "NORP": "lightseagreen"
}

# Load SpaCy model once
@st.cache_resource
def load_model():
    return spacy.load("en_core_web_sm")

nlp = load_model()

# Highlight function for HTML
def highlight_entities_html(doc):
    html = ""
    last_idx = 0
    for ent in doc.ents:
        html += doc.text[last_idx:ent.start_char]
        color = colors.get(ent.label_, "lightgrey")
        html += f'<span style="background-color:{color}; font-weight:bold;">{ent.text} ({ent.label_})</span>'
        last_idx = ent.end_char
    html += doc.text[last_idx:]
    return html

# Sidebar: Show entity color legend with descriptions
st.sidebar.header("Entity Legend")
for label, conll in spacy2conll.items():
    color = colors.get(label, "lightgrey")
    description = entity_descriptions.get(label, "No description available")
    st.sidebar.markdown(
        f'<div style="margin-bottom:8px;">'
        f'<span style="background-color:{color}; padding:4px; border-radius:4px; color:black;">{label}</span> '
        f'**→ {conll}**<br>'
        f'<small>{description}</small>'
        f'</div>',
        unsafe_allow_html=True
    )

# Main UI
st.title("Named Entity Recognition (NER) Highlighter")
st.write("Enter text and see detected entities highlighted with colors.")

user_input = st.text_area("Enter text here", height=150)

if st.button("Analyze Entities"):
    if user_input.strip():
        doc = nlp(user_input)
        if doc.ents:
            st.markdown(highlight_entities_html(doc), unsafe_allow_html=True)
        else:
            st.warning("No entities found.")
    else:
        st.error("Please enter some text.")